"""empty message

Revision ID: f7b37512bd53
Revises: d68eebeac2d0
Create Date: 2025-05-19 18:25:57.177161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7b37512bd53'
down_revision: Union[str, None] = 'd68eebeac2d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth', sa.Column('user_id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth', 'user_id')
    # ### end Alembic commands ###
